SELECT 
DIM_TEMPO.NUMERO_ANO
, FATO_PRESIDENCIA.ID_FABRICA
, FATO_PRESIDENCIA.ID_VENDEDOR
, FATO_PRESIDENCIA.ID_CLIENTE
, FATO_PRESIDENCIA.ID_PRODUTO
, SUM(FATO_PRESIDENCIA.FATURAMENTO) AS FATURAMENTO
, 1 AS CONTADORLINHA
FROM FATO_PRESIDENCIA
INNER JOIN DIM_TEMPO 
ON DIM_TEMPO.ID_TEMPO = FATO_PRESIDENCIA.ID_TEMPO
GROUP BY 
DIM_TEMPO.NUMERO_ANO
, FATO_PRESIDENCIA.ID_FABRICA
, FATO_PRESIDENCIA.ID_VENDEDOR
, FATO_PRESIDENCIA.ID_CLIENTE
, FATO_PRESIDENCIA.ID_PRODUTO